/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.MySQL;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form button_panel
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1400, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,175));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setEnabled(false);
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel3PropertyChange(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 450, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setEnabled(false);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel2PropertyChange(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 450, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51,100));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nomsg.png"))); // NOI18N
        jPanel2.add(jLabel4, "card2");

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 710, 610));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51,100));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 610));
        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/budgetpng.png"))); // NOI18N
        jPanel1.add(jLabel5, "card2");

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 600, 610));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("Budget of the day");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 410, 70));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home_cover_img2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel3PropertyChange
           // TODO add your handling code here:
           try {
               
            ResultSet rs = MySQL.search("SELECT * FROM `stock` WHERE `quantity`>'0' AND `quantity`<='2'");
            if(rs.next()){
            
            jLabel3.setEnabled(true);
            jLabel3.setText("Low Quantity Products are Available");
            jLabel3.setForeground(java.awt.Color.RED);
            
            jLabel4.setIcon(null);
            jLabel4.revalidate();
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/msg.png")));
            
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    
    }//GEN-LAST:event_jLabel3PropertyChange

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (jLabel3.getText().equals("Low Quantity Products are Available")) {
        QtyMsg pm = new QtyMsg();
        jPanel2.removeAll();
        jPanel2.add(pm);
        jPanel2.revalidate();
        jPanel2.repaint();
        jLabel3.setEnabled(false);
        this.resize(600, 610);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel2PropertyChange
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dNow = sdf.format(new Date());
            
            ResultSet rs = MySQL.search("SELECT * FROM `stock` WHERE `exd` > '"+dNow+"' AND `exd`<=('"+dNow+"' + interval 30 day)");
            if(rs.next()){
            
            jLabel2.setEnabled(true);
            jLabel2.setText("Expire Products are Available");
            jLabel2.setForeground(java.awt.Color.RED);
            
            jLabel4.setIcon(null);
            jLabel4.revalidate();
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/msg.png")));
            
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2PropertyChange

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (jLabel2.getText().equals("Expire Products are Available")) {
        ExdMsg em = new ExdMsg();
        jPanel2.removeAll();
        jPanel2.add(em);
        jPanel2.revalidate();
        jPanel2.repaint();
        jLabel2.setEnabled(false);
        this.resize(1400, 900);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Budget bg = new Budget();
        jPanel1.removeAll();
        jPanel1.add(bg);
        jPanel1.revalidate();
        jPanel1.repaint();
        this.resize(1400, 900);
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
